### ISSUE TITLE
in search of a main program

### ISSUE THREAD

**Issue by robert-dodier** [johshoff/gibbon#1]
Johannes, thanks for making gibbon available. It appears that gibbon is a library and there is no main function -- is that correct? Do you have a main function that you could commit? I am interested in Rust and I guess I can write my own main function but I am more interested in exploring the ideas in the Gorilla paper which you presented yesterday, so if you already have a main function I would be interested to try it. Thanks for any information, I appreciate your help. Robert Dodier.

**Comment by johshoff** [comment]
Thanks for your interest! Indeed, as it is a library it doesn't have a main function. I have a local change which adds an example directory with a main function. I will try to make a commit tonight or tomorrow.

**Comment by johshoff** [comment]
@robert-dodier I added an example of the usage. Hope this is helpful. Instructions to run them are in the readme: https://github.com/johshoff/gibbon#example

Happy to answer questions either here or on the rust meetup next week.

**Comment by robert-dodier** [comment]
Thanks a lot Johannes, it works for me. Looks good.
