### ISSUE TITLE
Panic on some inputs

### ISSUE THREAD

**Issue by That3Percent** [johshoff/gibbon#2]
Attempting to round trip some arrays results in a panic. This issue is prohibiting the use of gibbon in [Tree-Buf](https://github.com/That3Percent/tree-buf)

Here is one such array: `[-75.01536474599993, -75.00911189799993, 114.37647545700004]`. And the result:
```
thread 'broken_gorilla' panicked at 'attempt to shift left with overflow', .cargo\registry\src\github.com-1ecc6299db9ec823\gibbon-0.1.1\src\vec_stream.rs:94:21
```

This array is one of the smallest arrays I have found in a program that searches for panicking arrays among a slice of benchmark data I have, but there are many such sub-slices that panic.

I'm working on making this into a test case in a fork and am opening the issue to get the conversation started.

**Comment by That3Percent** [comment]
It seems this might be fixed on master, but a new version has not yet been pushed to crates.io? The version `0.1.1` on crates.io has a struct named `DoubleStream` but in the latest version this is named `DoubleStreamWriter`. The quick test that I wrote to reproduce the panic didn't panic with the latest repo.

**Comment by johshoff** [comment]
Hi! Thanks for the report. I've just published 0.1.2. Let me know if that fixes your issue.

**Comment by That3Percent** [comment]
Greetings @johshoff Thanks for the quick reply!

As I got more familiar with the API I was able to reproduce the problem. Submitting A PR now...

**Comment by That3Percent** [comment]
Interestingly, the test in the PR passes in release mode . This might be as simple as changing a `<<` to `x.checked_shl(y).unwrap_or(0)` as noted by this thread - https://users.rust-lang.org/t/intentionally-overflow-on-shift/11859/7

But, I'm not familiar enough with the algorithm to say for sure so be sure to check that this makes sense.

**Comment by johshoff** [comment]
Thanks for the bug report and the clear test case. Made it easy to fix!

The fix, if you're curious: https://github.com/johshoff/gibbon/commit/81e5afbd18a850cdb86fadef8fbb9ff67397f807

**Comment by johshoff** [comment]
As a warning, you might encounter several more bugs. This project was mainly written to learn the algorithm while reading the paper. It has been used a little bit, but not anywhere close to a production environment.
